// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrjL7x2oCy_GOwmCUVZjCajHyOTlk8eYw',
    appId: '1:230236666103:web:5bdfdbaf1a240b0fc7fbf2',
    messagingSenderId: '230236666103',
    projectId: 'greencity-office',
    authDomain: 'greencity-office.firebaseapp.com',
    storageBucket: 'greencity-office.appspot.com',
    measurementId: 'G-1LDJ0E9QDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC76AxWU2-p6G6Ye4-_-PxqStFlP_APQew',
    appId: '1:230236666103:android:72867f8c2b4799abc7fbf2',
    messagingSenderId: '230236666103',
    projectId: 'greencity-office',
    storageBucket: 'greencity-office.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkDmpkAHrFNsgQuC3-2MpfMl7sBsVFssE',
    appId: '1:230236666103:ios:da97def310563b4fc7fbf2',
    messagingSenderId: '230236666103',
    projectId: 'greencity-office',
    storageBucket: 'greencity-office.appspot.com',
    iosClientId: '230236666103-9jaqh6v6on2f3g2t2e529atp92cfaf2c.apps.googleusercontent.com',
    iosBundleId: 'greencity.sustentavel.office.greencitySustentavelOffice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkDmpkAHrFNsgQuC3-2MpfMl7sBsVFssE',
    appId: '1:230236666103:ios:da97def310563b4fc7fbf2',
    messagingSenderId: '230236666103',
    projectId: 'greencity-office',
    storageBucket: 'greencity-office.appspot.com',
    iosClientId: '230236666103-9jaqh6v6on2f3g2t2e529atp92cfaf2c.apps.googleusercontent.com',
    iosBundleId: 'greencity.sustentavel.office.greencitySustentavelOffice',
  );
}
